#spring:
#  application:
#    name: favouriteservice
#  datasource:
#    url: ${MYSQL_CI_URL}
#    username: ${MYSQL_USER}
#    password: ${MYSQL_PASSWORD}
#  jpa:
#   hibernate:
#    ddl-auto: update
#   show-sql: true
#server:
# port: 8080

spring:
  application:
    name: favouriteservice
  datasource:
    url: jdbc:mysql://localhost:3306/matchdb
    username: root
    password: root123
  jpa:
   hibernate:
    ddl-auto: update
   show-sql: true
server:
 port: 8090

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:9003/eureka