FROM java:8-jre
WORKDIR usr/src
ADD ./target/orchestrationService-0.0.1-SNAPSHOT.jar /usr/src/orchestrationService-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","orchestrationService-0.0.1-SNAPSHOT.jar"]
